/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdateRouteImport } from './routes/update'
import { Route as SitemapDottxtRouteImport } from './routes/sitemap[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PopularRouteImport } from './routes/popular'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetailMangaIdRouteImport } from './routes/detail.$mangaId'
import { Route as ChapterChapterIdRouteImport } from './routes/chapter.$chapterId'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const UpdateRoute = UpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDottxtRoute = SitemapDottxtRouteImport.update({
  id: '/sitemap.txt',
  path: '/sitemap.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularRoute = PopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailMangaIdRoute = DetailMangaIdRouteImport.update({
  id: '/detail/$mangaId',
  path: '/detail/$mangaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterChapterIdRoute = ChapterChapterIdRouteImport.update({
  id: '/chapter/$chapterId',
  path: '/chapter/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/popular': typeof PopularRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.txt': typeof SitemapDottxtRoute
  '/update': typeof UpdateRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/detail/$mangaId': typeof DetailMangaIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/popular': typeof PopularRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.txt': typeof SitemapDottxtRoute
  '/update': typeof UpdateRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/detail/$mangaId': typeof DetailMangaIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/home': typeof HomeRoute
  '/popular': typeof PopularRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.txt': typeof SitemapDottxtRoute
  '/update': typeof UpdateRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/detail/$mangaId': typeof DetailMangaIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/home'
    | '/popular'
    | '/robots.txt'
    | '/sitemap.txt'
    | '/update'
    | '/chapter/$chapterId'
    | '/detail/$mangaId'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/home'
    | '/popular'
    | '/robots.txt'
    | '/sitemap.txt'
    | '/update'
    | '/chapter/$chapterId'
    | '/detail/$mangaId'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/home'
    | '/popular'
    | '/robots.txt'
    | '/sitemap.txt'
    | '/update'
    | '/chapter/$chapterId'
    | '/detail/$mangaId'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  HomeRoute: typeof HomeRoute
  PopularRoute: typeof PopularRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDottxtRoute: typeof SitemapDottxtRoute
  UpdateRoute: typeof UpdateRoute
  ChapterChapterIdRoute: typeof ChapterChapterIdRoute
  DetailMangaIdRoute: typeof DetailMangaIdRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update': {
      id: '/update'
      path: '/update'
      fullPath: '/update'
      preLoaderRoute: typeof UpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.txt': {
      id: '/sitemap.txt'
      path: '/sitemap.txt'
      fullPath: '/sitemap.txt'
      preLoaderRoute: typeof SitemapDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail/$mangaId': {
      id: '/detail/$mangaId'
      path: '/detail/$mangaId'
      fullPath: '/detail/$mangaId'
      preLoaderRoute: typeof DetailMangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$chapterId': {
      id: '/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/chapter/$chapterId'
      preLoaderRoute: typeof ChapterChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  HomeRoute: HomeRoute,
  PopularRoute: PopularRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDottxtRoute: SitemapDottxtRoute,
  UpdateRoute: UpdateRoute,
  ChapterChapterIdRoute: ChapterChapterIdRoute,
  DetailMangaIdRoute: DetailMangaIdRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
