/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PopularRouteImport } from './routes/popular'
import { Route as GenreRouteImport } from './routes/genre'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpdateIndexRouteImport } from './routes/update.index'
import { Route as ReadMangaIdRouteImport } from './routes/read.$mangaId'
import { Route as ChapterChapterIdRouteImport } from './routes/chapter.$chapterId'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const PopularRoute = PopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreRoute = GenreRouteImport.update({
  id: '/genre',
  path: '/genre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateIndexRoute = UpdateIndexRouteImport.update({
  id: '/update/',
  path: '/update/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadMangaIdRoute = ReadMangaIdRouteImport.update({
  id: '/read/$mangaId',
  path: '/read/$mangaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterChapterIdRoute = ChapterChapterIdRouteImport.update({
  id: '/chapter/$chapterId',
  path: '/chapter/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/genre': typeof GenreRoute
  '/popular': typeof PopularRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/read/$mangaId': typeof ReadMangaIdRoute
  '/update/': typeof UpdateIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/genre': typeof GenreRoute
  '/popular': typeof PopularRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/read/$mangaId': typeof ReadMangaIdRoute
  '/update': typeof UpdateIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/genre': typeof GenreRoute
  '/popular': typeof PopularRoute
  '/chapter/$chapterId': typeof ChapterChapterIdRoute
  '/read/$mangaId': typeof ReadMangaIdRoute
  '/update/': typeof UpdateIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/genre'
    | '/popular'
    | '/chapter/$chapterId'
    | '/read/$mangaId'
    | '/update/'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/genre'
    | '/popular'
    | '/chapter/$chapterId'
    | '/read/$mangaId'
    | '/update'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/genre'
    | '/popular'
    | '/chapter/$chapterId'
    | '/read/$mangaId'
    | '/update/'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenreRoute: typeof GenreRoute
  PopularRoute: typeof PopularRoute
  ChapterChapterIdRoute: typeof ChapterChapterIdRoute
  ReadMangaIdRoute: typeof ReadMangaIdRoute
  UpdateIndexRoute: typeof UpdateIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre': {
      id: '/genre'
      path: '/genre'
      fullPath: '/genre'
      preLoaderRoute: typeof GenreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update/': {
      id: '/update/'
      path: '/update'
      fullPath: '/update/'
      preLoaderRoute: typeof UpdateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$mangaId': {
      id: '/read/$mangaId'
      path: '/read/$mangaId'
      fullPath: '/read/$mangaId'
      preLoaderRoute: typeof ReadMangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$chapterId': {
      id: '/chapter/$chapterId'
      path: '/chapter/$chapterId'
      fullPath: '/chapter/$chapterId'
      preLoaderRoute: typeof ChapterChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenreRoute: GenreRoute,
  PopularRoute: PopularRoute,
  ChapterChapterIdRoute: ChapterChapterIdRoute,
  ReadMangaIdRoute: ReadMangaIdRoute,
  UpdateIndexRoute: UpdateIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
